version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: EventCode
    environment:
     POSTGRES_DB: EventClean
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres


